### PR TITLE
Add: Test for setup.py. There are some hacks for Travis

### PR DESCRIPTION
**Pull request by Seb-Solon**

### CODE REVIEW

**Comment by ddurieux** [comment]
It's possible to have script in sh instead bash, because I don't use / want to install bash in my FreeBSD?

**Comment by Seb-Solon** [comment]
Well can we do it in another PR ? There are some bash substitution I have to find how to remove.

**Comment by gst** [comment]
I think I'm ok for the merge.. 
@Seb-Solon  you had not some things to finish / enhance ? 
if not then I'll merge..

**Comment by Seb-Solon** [comment]
If @ddurieux is ok to change to sh in another Pr yeah we can merge :)

**Pull request merged**
