### PR TITLE
Enh: Pylint (W0403)

### PR DESCRIPTION
**Pull request by ddurieux**

### CODE REVIEW

**Comment by Seb-Solon** [comment]
Seems legit. I don't know the diff beween this and local import. Is it very different? ping @gst

**Comment by Seb-Solon** [comment]
OK i found some doc : http://stackoverflow.com/questions/4209641/absolute-vs-explicit-relative-import-of-python-module

I guess absolute are better then :)

**Comment by gst** [comment]
sorry I had not seen (until now) your ping ;)

absolutes and relatives import are both possible, effectively. and there are use case where relatives imports are really/clearly better (not to say absolutely required)..
but we don't have such use cases here.

So always choosing/using the  absolute side/possibility is OK for me, and it's better to always use the same features the same way ; that's simply more consistent also :)

So +1  ;)

**Comment by Seb-Solon** [comment]
Related to #4, #87, #262 and naparuba/shinken#1393 .

**Pull request merged**
