### PR TITLE
Add a Gitter chat badge to README.rst

### PR DESCRIPTION
**Pull request by gitter-badger**
### Alignak-monitoring/alignak now has a Chat Room on Gitter

@gst has just created a chat room. You can visit it here: [https://gitter.im/Alignak-monitoring/alignak](https://gitter.im/Alignak-monitoring/alignak?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&content=body_link).

This pull-request adds this badge to your README.rst:

[Gitter](https://gitter.im/Alignak-monitoring/alignak?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=body_badge)

If my aim is a little off, please [let me know](https://github.com/gitterHQ/readme-badger/issues).

Happy chatting.

PS: [Click here](https://gitter.im/settings/badger/opt-out) if you would prefer not to receive automatic pull-requests from Gitter in future.

### CODE REVIEW

**Comment by aviau** [comment]
I prefer IRC over proprietary chat.

**Comment by ddurieux** [comment]
+1 for irc...

**Comment by gst** [comment]
I prefer a chat with recent history nativly included in the main window/widget ..  :p  
And with full archive also available of the whole history of the chat room.
And icing on the cake : it also has notifications from github events included .. (and others plugins, not yet looked at all that).

Yes, I prefer also "free" tools over proprietary ones, but I'm also pragmatic : this one offer, from start/scratch more than any bare IRC client .. (and there can exist proprietary IRC clients also .. ;) )

**Comment by gst** [comment]
This is also a very good point : 

"natively" included within github by the mean of the badge in the README page.

So, I'd bet it, we'll get certainly more people to join it than if it was a plain IRC room..

**Comment by mohierf** [comment]
+1 for @gst  ... the native Github inclusion seems a very good feature !

**Pull request merged**
