### PR TITLE
WiP - Docker images for Alignak

### PR DESCRIPTION
**Pull request by mohierf**

### CODE REVIEW

**Comment by palvarezcordoba** [comment]
Hi @mohierf, if you need help with docker images, I would be happy to collaborate :)

**Comment by mohierf** [comment]
Thanks @palvarezcordoba :wink: 
If you have a few time to have a look into the images I prepared, I am interested in your suggestions for improvements. I built a docker-compose.yml file which aims to easily run Alignak + Web UI + Graphite

**Comment by palvarezcordoba** [comment]
Hi @mohierf 
Why did you deleted the docker branch?

**Comment by mohierf** [comment]
Hi @palvarezcordoba 
Sorry, it was a mistake... I refactored to make something cleaner and I renamed the branch as docker-images, but I removed the docker branch by mistake ... Iwill push my docker-images branch very soon!

**Pull request closed without merging**
