### PR TITLE
[wip] Clean: dropped the stats module and all its usage

### PR DESCRIPTION
**Pull request by gst**

### CODE REVIEW

**Comment by Seb-Solon** [comment]
I disagree. I think we should drop only the part that send it to an external website. The fact we want to collect stats is good. Maybe it's a module job but still the data collect is necessary.

**Comment by gst** [comment]
okay, will see that.

**Comment by ddurieux** [comment]
Yes performances metrics can be important. I don't think it's possible to use a module for that.

**Comment by mohierf** [comment]
I agree with @Seb-Solon and @ddurieux ... collecting metrics from Alignak core activity is important. Those metrics should be sent to an external module which will forward to Graphite or Statsd ?

**Comment by ddurieux** [comment]
We have removed specific statsd to external website, now have only statsd functions

**Pull request closed without merging**
