### PR TITLE
Remove test_shebang.sh

### PR DESCRIPTION
**Pull request by gst**
overkill and anyway, IMO, no file of the package should have a shebang.

the daemons will get a totally clean script file thanks to pbr entry_scripts.

### CODE REVIEW

**Comment by ddurieux** [comment]
Yes but no, if you remove the chebang test, you need to add a new :p

**Comment by gst** [comment]
no because there shouldn't be any shebang to any python module(/file) of the alignak package.

> __the daemons will get a totally clean script file thanks to pbr entry_scripts.__

**Comment by gst** [comment]
0.00s$ sh test/test_shebang.sh
sh: 0: Can't open test/test_shebang.sh
The command "sh test/test_shebang.sh" exited with 127.

**Comment by gst** [comment]
fion forgot to remove call to test_shebang.sh.. ;)  now corrected.

for reminder:  https://github.com/Alignak-monitoring/alignak/pull/39#discussion_r31255647

**Pull request merged**
