### PR TITLE
[wip] Fix right of var/run/alignak and var/log/alignak. closes #247

### LINKED ISSUE #247: Alignak start - directory access problem
After installing from source code, Alignak does not start when launched from the `alignak` user account: 
```
[1447681997] WARNING: [Alignak] Cannot call the additional groups setting with initgroups (Operation not permitted)
[1447681997] CRITICAL: [Alignak] I got an unrecoverable error. I have to exit.
[1447681997] CRITICAL: [Alignak] You can get help at https://github.com/Alignak-monitoring/alignak
[1447681997] CRITICAL: [Alignak] If you think this is a bug, create a new ticket includingdetails mentioned in the README
[1447681997] CRITICAL: [Alignak] Back trace of the error: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/alignak/daemons/arbiterdaemon.py", line 578, in main
    self.do_daemon_init_and_start()
  File "/usr/local/lib/python2.7/dist-packages/alignak/daemon.py", line 651, in do_daemon_init_and_start
    self.check_parallel_run()
  File "/usr/local/lib/python2.7/dist-packages/alignak/daemon.py", line 477, in check_parallel_run
    self.__open_pidfile()
  File "/usr/local/lib/python2.7/dist-packages/alignak/daemon.py", line 461, in __open_pidfile
    raise InvalidPidFile(err)
InvalidPidFile: [Errno 13] Permission denied: u'/usr/local/var/run/alignak/arbiterd.pid'

Traceback (most recent call last):
  File "/usr/local/bin/alignak-arbiter", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/alignak/bin/alignak_arbiter.py", line 128, in main
    daemon.main()
  File "/usr/local/lib/python2.7/dist-packages/alignak/daemons/arbiterdaemon.py", line 578, in main
    self.do_daemon_init_and_start()
  File "/usr/local/lib/python2.7/dist-packages/alignak/daemon.py", line 651, in do_daemon_init_and_start
    self.check_parallel_run()
  File "/usr/local/lib/python2.7/dist-packages/alignak/daemon.py", line 477, in check_parallel_run
    self.__open_pidfile()
  File "/usr/local/lib/python2.7/dist-packages/alignak/daemon.py", line 461, in __open_pidfile
    raise InvalidPidFile(err)
alignak.daemon.InvalidPidFile: [Errno 13] Permission denied: u'/usr/local/var/run/alignak/arbiterd.pid'
```

### PR DESCRIPTION
**Pull request by ddurieux**

### CODE REVIEW

**Comment by Seb-Solon** [comment]
You should do this in import hooks no directly in setup.py. You need the directory variable, not the horcoded value. The chown is only needed in non root or non virtualenv setup.

**Comment by ddurieux** [comment]
import hooks?

**Comment by Seb-Solon** [comment]
install hooks sorry  : https://github.com/Alignak-monitoring/alignak/blob/develop/install_hooks.py

**Comment by mohierf** [comment]
This PR is no more useful. The directories ownership and rights are managed in the install hooks of the new setup.py script. I propose that you close it @ddurieux

**Comment by mohierf** [comment]
@ddurieux: I close this PR that is not anymore useful ...

**Pull request closed without merging**
