### PR TITLE
Host dependency exception when host not found

### LINKED ISSUE #455: Host dependency makes an exception
If an host involved in a dependency does not exist or is not is the same realm as another host involved inthe dependency, and exception is raised:

```
[2016-10-13 08:07:45 CEST] CRITICAL: [alignak.daemon] I got an unrecoverable error. I have to exit.
[2016-10-13 08:07:45 CEST] CRITICAL: [alignak.daemon] You can get help at https://github.com/Alignak-monitoring/alignak
[2016-10-13 08:07:45 CEST] CRITICAL: [alignak.daemon] If you think this is a bug, create a new ticket including details mentioned in the README
[2016-10-13 08:07:45 CEST] CRITICAL: [alignak.daemon] -----
[2016-10-13 08:07:45 CEST] CRITICAL: [alignak.daemon] Back trace of the error: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/alignak/daemons/arbiterdaemon.py", line 518, in main
    self.load_monitoring_config_file()
  File "/usr/local/lib/python2.7/dist-packages/alignak/daemons/arbiterdaemon.py", line 341, in load_monitoring_config_file
    self.conf.linkify()
  File "/usr/local/lib/python2.7/dist-packages/alignak/objects/config.py", line 1351, in linkify
    self.hostdependencies.linkify(self.hosts, self.timeperiods)
  File "/usr/local/lib/python2.7/dist-packages/alignak/objects/hostdependency.py", line 204, in linkify
    self.linkify_h_by_hd(hosts)
  File "/usr/local/lib/python2.7/dist-packages/alignak/objects/hostdependency.py", line 270, in linkify_h_by_hd
    hostdep.inherits_parent)
  File "/usr/local/lib/python2.7/dist-packages/alignak/objects/schedulingitem.py", line 3115, in add_act_dependency
    son = self[son_id]
  File "/usr/local/lib/python2.7/dist-packages/alignak/objects/item.py", line 1011, in __getitem__
    return self.items[key] if key else None
KeyError: u'm2m'

```

### PR DESCRIPTION
**Pull request by mohierf**
Closes #455 

---
This fix is also included in #440 but it cannot be merged now...

### CODE REVIEW

**Comment by ddurieux** [comment]
yes and no, this must be verified in _is_correct_ function

**Comment by mohierf** [comment]
Not possible ... it is too late in the `is_correct` function ... the exception occurs before calling it!

**Comment by ddurieux** [comment]
The linkify is called after the is_correct in arbiterdaemon, so it will be detected before here

**Comment by mohierf** [comment]
To be done in #440

**Pull request merged**
