### PR TITLE
Enh/clean: replaced pycurl by requests in HTTPClient.

### PR DESCRIPTION
**Pull request by gst**
Almost complete rewrite of http_client module using requests instead of pycurl.

already quite simpler and, more important certainly, this will allow us to try pypy, very soon..

NB: the http_client module is not **specifically** tested as far as I know / see .. 
though, 45% of it is covered by some test : https://coveralls.io/builds/2802007/source?filename=alignak%2Fhttp_client.py

but I've run my alignak dev daemons with this commit and the conf / etc were correctly dispatched, etc..

### CODE REVIEW

**Comment by gst** [comment]
will fix https://github.com/Alignak-monitoring/alignak/issues/60

**Comment by gst** [comment]
comment ?

**Comment by Seb-Solon** [comment]
Well, you will tell me I'm bothering you with test but IMO this change is kinda risky because we don't have functional tests right now.

> the http_client module is not specifically tested as far as I know / see .. 

The coverage for your PR is 58% : https://coveralls.io/builds/2801982/source?filename=alignak%2Fhttp_client.py better then previously actually. 

I can see in both cases only the get seems to be covered. What about post and put? I don't know where the get is covered but that could be great to see if we can have the other called. What do you think?

**Comment by gst** [comment]
effectively only the `get` is covered (by which test is something else, I'd guess by more than one probably)..

but I agree that the `post` and `put` which are defined (&used) *should* be as well be covered by some test(s) and even explicitely (and so the `get` as well)..  that was never done yet ;)

problem is that the state of the `HTTPDaemon` (the server part against which this http_client applies) doesn't necessary makes it easy.. though.. well in fact I started writting one new test file doing exactly this actually.. I was a bit after its fresh start and was at the point to think on how to more easily get to the `put` and `post` (and `get`) of an HTTPClient instance being usable in some easy configuration so in a TestCase instance..

give me some minutes and I'll check if I can get above very quickly advanced .. :p

**Comment by gst** [comment]
in fact, IMHO, the "http_daemon" (and its related `http_thread` (attribute of Daemon) as well ; in fact http_thread & http_daemon objects should be merged into one single entity/object) **should** be completely rewritten as this http_client is now done..

also the fact that there is 2 possible http backends (which have some differences in how they run which leads to some distinct problems between them.. ho well..) is.. err.. don't know..
and otherwise the "quality" of that http_daemon file is not very good.. really.

but well.. I give a (fast) try on my previous comment first (we never know it'd be that easy.. (hmm)).

**Comment by gst** [comment]
ok I could got something good and quite easy.. but had not time left to push it.. I'll try to do that tonight or later..

**Comment by gst** [comment]
+ tests added, 

+ executed with pycurl old http_client version -> OK  (when there isn't some weird timing issues blocking the full test.. but I now know more about them and will be able to provide a fix).
+ tests with requests version are also ok (if no timing issue, otherwise : relaunch build/tests).

**Pull request merged**
