### PR TITLE
[wip] Force dict to display as string in logger

### PR DESCRIPTION
**Pull request by ddurieux**

### CODE REVIEW

**Comment by Seb-Solon** [comment]
Str(dict) is different from dict.__str__() ?

**Comment by ddurieux** [comment]
Yes because dictionary has not str() function

**Comment by gst** [comment]
??

```
>>> {}.__str__()
'{}'
```

if its not displayed as a string in a logger call, as/like what would it be displayed ??

**Comment by ddurieux** [comment]
Ok I close

**Pull request closed without merging**
