### PR TITLE
Enh len of list comprehension to len of generator

### PR DESCRIPTION
**Pull request by gst**
Many pythonic changes which should result in many (small but still) performance improvement changes..

I measured most of them but some aren't that obvious.. concerning the perf improvement.  
if one want we can talk about it..

### CODE REVIEW

**Comment by ddurieux** [comment]
Add test for cover these functions please to be sure these functions are not broken

**Comment by gst** [comment]
> Add test for cover these functions please to be sure these functions are not broken

all these changes are really "*easy*" changes and according to the travis build they aren't broken ;)

**Comment by gst** [comment]
what surprised me is that : 

`len([ x for x in sequence if filter(x) ])`  forms aren't necessarily always slower than the more pythonic form `sum(1 for x in sequence if filter(x))`  (which doesn't creates unnecessarily a temp list before doing it's len()).

but the difference is very little when the former is quicker than the later.

**Comment by gst** [comment]
> what surprised me is that :

ah ! it depends how the sum() argument is constructed !

```
In [7]: timeit.timeit("len([x for x in lst if filt(x)])", "lst = list(range(10000)) ; filt = lambda v: v%13!=0", number=100)
Out[7]: 0.13385295867919922

In [8]:

In [8]: timeit.timeit("sum(filter(filt, lst))", "lst = list(range(10000)) ; filt = lambda v: v%13!=0", number=100)
Out[8]: 0.1352519989013672

In [9]:

In [9]: timeit.timeit("sum(filter(filt, lst))", "lst = list(range(10000)) ; filt = lambda v: v%13!=0", number=100)
Out[9]: 0.1256258487701416

In [10]: timeit.timeit("sum(filter(filt, lst))", "lst = list(range(10000)) ; filt = lambda v: v%13!=0", number=100)
Out[10]: 0.1333022117614746

In [11]: timeit.timeit("sum(filter(filt, lst))", "lst = list(range(10000)) ; filt = lambda v: v%13!=0", number=1000)
Out[11]: 0.9786028861999512

In [12]: timeit.timeit("len([x for x in lst if filt(x)])", "lst = list(range(10000)) ; filt = lambda v: v%13!=0", number=1000)
Out[12]: 1.2255499362945557

In [13]: timeit.timeit("len([x for x in lst if filt(x)])", "lst = list(range(10000)) ; filt = lambda v: v%13!=0", number=1000)
Out[13]: 1.2320811748504639

In [14]: timeit.timeit("sum(filter(filt, lst))", "lst = list(range(10000)) ; filt = lambda v: v%13!=0", number=1000)
Out[14]: 0.9566860198974609

In [15]: timeit.timeit("sum(filter(filt, lst))", "lst = list(range(10000)) ; filt = lambda v: v%13!=0", number=1000)
Out[15]: 1.0634419918060303
```

So I'll make another pass and see if I can get that.

**Comment by gst** [comment]
so sum() with an "if-generator" `sum(x for x in lst if y(x))` is a little slower than sum with a filter() applied to the generator : `sum(filter(lst, y))`  and this one is even more pythonic than the previous.. So I'll made an update.

**Comment by gst** [comment]
rebased on develop..

**Comment by Seb-Solon** [comment]
"little DRY" is IMO not a valid commit message.

**Pull request merged**
