### PR TITLE
Added coverage badge to README

### PR DESCRIPTION
**Pull request by gst**
TODO: make coverage build to succeed

### CODE REVIEW

**Comment by aviau** [comment]
Fix coverage before you merge this,

**Comment by gst** [comment]
actually I wanted to use the badge to see / know when the "build" will be ok.. but well..

**Comment by gst** [comment]
what's quite boring is that coveralls.io is *very* slow at generating its results..

**Comment by aviau** [comment]
You can go on the coveralls website. You dont need the badge to see if the build works.

**Comment by gst** [comment]
yeah but coveralls.io, not only *very* slow, is also not that clear .. what I want to get is the badge status ok (whatever is the %) ; so my first merge of it before all ;)

**Pull request merged**
