### PR TITLE
Fix #365: missing service_description for a service breaks the configuration loading

### LINKED ISSUE #365: Service defined with no service_description breaks Alignak loading
When loading a configuration where a service is missing the `service_description` attribute, the configuration loading raises an exception:
```
[1474889898] CRITICAL: [Alignak] I got an unrecoverable error. I have to exit.
[1474889898] CRITICAL: [Alignak] You can get help at https://github.com/Alignak-monitoring/alignak
[1474889898] CRITICAL: [Alignak] If you think this is a bug, create a new ticket includingdetails mentioned in the README
[1474889898] CRITICAL: [Alignak] Back trace of the error: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/alignak/daemons/arbiterdaemon.py", line 525, in main
    self.load_config_file()
  File "/usr/local/lib/python2.7/dist-packages/alignak/daemons/arbiterdaemon.py", line 313, in load_config_file
    self.conf.explode()
  File "/usr/local/lib/python2.7/dist-packages/alignak/objects/config.py", line 1632, in explode
    self.triggers)
  File "/usr/local/lib/python2.7/dist-packages/alignak/objects/service.py", line 1631, in explode
    if host and host.is_excluded_for(service):
  File "/usr/local/lib/python2.7/dist-packages/alignak/objects/host.py", line 423, in is_excluded_for
    return self.is_excluded_for_sdesc(service.service_description, service.is_tpl())
AttributeError: service_description
```

As an example, this service definition:
```
define service {
        use                             generic-windows-host
        host_name                 test_host
	check_command        check_cpu_wmi!70!80!ssa
}
```

### PR DESCRIPTION
**Pull request by mohierf**
I did not included any test because of the current tests refactoring ... 

But when running the arbiter with the -V options, I got:
```
[1474890355] ERROR: [Alignak] [service::generic-windows-host] service_description property not set
[1474890355] ERROR: [Alignak] [service::generic-windows-host] a service has been defined without service_description in /home/alignak/conf/host.cfg:14
[1474890355] ERROR: [Alignak] [service::generic-windows-host] a service item has been defined without unique_key in /home/alignak/conf/host.cfg:14
[1474890355] ERROR: [Alignak] [items] In generic-windows-host is incorrect ; from /home/alignak/conf_cnaf/conf/host.cfg:14
[1474890355] ERROR: [Alignak] 	services conf incorrect!!

```

instead of the exception !

### CODE REVIEW

**Comment by Seb-Solon** [comment]
Please squash / merge the commit so that I can merge the PR

**Comment by mohierf** [comment]
Sorry @Seb-Solon : I do not understand what you mean. This PR can be merged directly onto the develop branch. What is the idea behind squash / merge ?

**Comment by Seb-Solon** [comment]
The idea is to have a single commit for this PR. The second commit is a fix of something introduced in the first. At the end the pr is just a 2 lines diff

**Comment by mohierf** [comment]
I never did this ... but I will try :wink:

**Comment by mohierf** [comment]
I di  some local modifications on my repo to make tests ... the most simple solution for me is to delete and re-create this PR/branch. As of it, I close

**Pull request closed without merging**
