### PR TITLE
Pylint

### PR DESCRIPTION
**Pull request by titilambert**

### CODE REVIEW

**Comment by Seb-Solon** [comment]
NOOOOOOOOOOOOOOOOOOOOOOO

**Comment by Seb-Solon** [comment]
Revert that please. If brok is new object class pickle fails. remember the following : 
https://github.com/naparuba/shinken/pull/1526
https://github.com/naparuba/shinken/pull/1522

**Comment by gst** [comment]
there should be another PR to do the correct thing (allow thoses classes to be serializable/picklable) : 

define \_\_getstate\_\_ and \_\_setstate\_\_ where appropriate, or better: inherits/subclass something which is picklable .. (say ~~shinken~~alignak.object.item.Item ? ;))

**Comment by ddurieux** [comment]
This PR has been reverted, see https://github.com/Alignak-monitoring/alignak/pull/146

**Comment by Seb-Solon** [comment]
Related to #4, #87, #262 and naparuba/shinken#1393 .

**Pull request merged**
