### PR TITLE
[wip] Convert brok class to new style class

### PR DESCRIPTION
**Pull request by ddurieux**

### CODE REVIEW

**Comment by Seb-Solon** [comment]
Nope. It will fail at pickling

**Comment by ddurieux** [comment]
when you do cpikle?

**Comment by Seb-Solon** [comment]
Please have a look at #146 #144 naparuba/shinken#1526 and naparuba/shinken#1522.

**Comment by gst** [comment]
```
  File "/home/travis/build/Alignak-monitoring/alignak/alignak/objects/satellitelink.py", line 487, in push_broks

    self.con.post('push_broks', {'broks': broks}, wait='long')

  File "/home/travis/build/Alignak-monitoring/alignak/alignak/http_client.py", line 181, in post

    args[k] = zlib.compress(cPickle.dumps(v), 2)

  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/copy_reg.py", line 77, in _reduce_ex

    raise TypeError("a class that defines __slots__ without "

TypeError: a class that defines __slots__ without defining __getstate__ cannot be pickled
```

the error is 100% clear : 
either we not use __slots__,
either we implement \_\_getstate\_\_ and \_\_setstate\_\_

I think the latter is more appropriate..

**Comment by gst** [comment]
first found possibility :

```
class SlotPickleMixin(object):
    def __getstate__(self):
        return dict(
            (slot, getattr(self, slot))
            for slot in self.__slots__
            if hasattr(self, slot)
        )

    def __setstate__(self, state):
        for slot, value in state.items():
            setattr(self, slot, value)
```

from: http://code.activestate.com/recipes/578433-mixin-for-pickling-objects-with-__slots__/

second possibility from http://stackoverflow.com/a/3523501/2451329  : 

`cPickle.dumps(obj, -1 or 2)`

Not sure one of them is really better over the other one..

**Comment by ddurieux** [comment]
It's added in branch bigrework

**Pull request closed without merging**
