### PR TITLE
Fix linkify templates for commands and triggers

### PR DESCRIPTION
**Pull request by ddurieux**

### CODE REVIEW

**Comment by Seb-Solon** [comment]
What parameters were not linked properly?  It could be great to have a test case to see the difference in the objects

**Comment by ddurieux** [comment]
These two objects don't have management of templates and I think it could be a good idea.
If you're ok with that, I will add tests

**Comment by Seb-Solon** [comment]
well triggers templates, it's hard for me to see the usage. Command why not, I don't have a use case but i'm pretty sure we can have some.

**Comment by ddurieux** [comment]
Yes it's a non-sense

**Pull request closed without merging**
