### PR TITLE
Enh Pylint c0103

### PR DESCRIPTION
**Pull request by Seb-Solon**
I did not do the whole rule. So you may think I forgot some variable.

For now I only did local variable name (not functions names and not constants names)

```
:invalid-name (C0103): *Invalid %s name "%s"%s*
  Used when the name doesn't match the regular expression associated to its type
  (constant, variable, class...). This message belongs to the basic checker.
```

Regex is in .pylintrc 

```
# Regular expression matching correct variable names
variable-rgx=[a-z_][a-z0-9_]{2,30}$
```

### CODE REVIEW

**Comment by gst** [comment]
reviewing in progress..  1% so far.. ;)

**Comment by gst** [comment]
hmm.. I can reproduce this test error using this branch :  

```
gstarck@taf 10:02 $ nosetests -xv test_dateranges.py:TestDataranges.test_weekdaydaterange_start_end_time
test_weekdaydaterange_start_end_time (test_dateranges.TestDataranges) ... FAIL

======================================================================
FAIL: test_weekdaydaterange_start_end_time (test_dateranges.TestDataranges)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/gstarck/work/work/SFL/Supervision/alignak/test/test_dateranges.py", line 139, in test_weekdaydaterange_start_end_time
    self.assertEqual(start, ret[0])
AssertionError: 1442203200.0 != 1439179200.0
-------------------- >> begin captured stdout << ---------------------

################################################################################
#                                                                              #
#     test_dateranges.TestDataranges.test_weekdaydaterange_start_end_time      #
#                                                                              #
################################################################################


--------------------- >> end captured stdout << ----------------------
-------------------- >> begin captured logging << --------------------
Alignak: ERROR: Encoding detection error= StringIO instance has no attribute 'encoding'
Alignak: INFO: [config] opening 'etc/alignak_1r_1h_1s.cfg' configuration file
Alignak: INFO: Processing object config file 'etc/standard/hosts.cfg'
Alignak: INFO: Processing object config file 'etc/standard/services.cfg'
Alignak: INFO: Processing object config file 'etc/standard/contacts.cfg'
Alignak: INFO: Processing object config file 'etc/1r_1h_1s/commands.cfg'
Alignak: INFO: Processing object config file 'etc/1r_1h_1s/test_specific.cfg'
Alignak: INFO: Processing object config file 'etc/standard/timeperiods.cfg'
Alignak: INFO: Processing object config file 'etc/standard/hostgroups.cfg'
Alignak: INFO: Processing object config file 'etc/standard/servicegroups.cfg'
Alignak: INFO: Processing object config file 'etc/standard/alignak-specific.cfg'
Alignak: INFO: Processing object config file 'etc/resource.cfg'
Alignak: WARNING: Guessing the property temp_path type because it is not in Config object properties
Alignak: WARNING: Guessing the property p1_file type because it is not in Config object properties
Alignak: WARNING: Guessing the property daemon_dumps_core type because it is not in Config object properties
Alignak: WARNING: There is no arbiter, I add one in localhost:7770
Alignak: WARNING: I autogenerated some Arbiter modules, please look at your configuration
Alignak: WARNING: Module NamedPipe-Autogenerated was autogenerated
Alignak: WARNING: No scheduler defined, I add one at localhost:7768
Alignak: WARNING: No poller defined, I add one at localhost:7771
Alignak: WARNING: No reactionner defined, I add one at localhost:7769
Alignak: WARNING: No broker defined, I add one at localhost:7772
Alignak: WARNING: No realms defined, I add one at Default
Alignak: INFO: Tagging Default-Poller with realm Default
Alignak: INFO: Tagging Default-Broker with realm Default
Alignak: INFO: Tagging Default-Reactionner with realm Default
Alignak: INFO: Tagging Default-Scheduler with realm Default
Alignak: INFO: Default: (in/potential) (schedulers:1) (pollers:1/1) (reactionners:1/1) (brokers:1/1) (receivers:0/0)
Alignak: INFO: Running pre-flight check on configuration data...
Alignak: INFO: Checking global parameters...
Alignak: INFO: Checking hosts...
Alignak: WARNING: [host::test_host_0] Guessing the property address6 type because it is not in Host object properties
Alignak: INFO: 	Checked 2 hosts
Alignak: INFO: Checking hostgroups...
Alignak: INFO: 	Checked 12 hostgroups
Alignak: INFO: Checking contacts...
Alignak: INFO: 	Checked 1 contacts
Alignak: INFO: Checking contactgroups...
Alignak: INFO: 	Checked 2 contactgroups
Alignak: INFO: Checking notificationways...
Alignak: INFO: 	Checked 1 notificationways
Alignak: INFO: Checking escalations...
Alignak: INFO: 	Checked 0 escalations
Alignak: INFO: Checking services...
Alignak: INFO: 	Checked 1 services
Alignak: INFO: Checking servicegroups...
Alignak: INFO: 	Checked 12 servicegroups
Alignak: INFO: Checking timeperiods...
Alignak: INFO: 	Checked 1 timeperiods
Alignak: INFO: Checking commands...
Alignak: INFO: 	Checked 10 commands
Alignak: INFO: Checking hostsextinfo...
Alignak: INFO: 	Checked 0 hostsextinfo
Alignak: INFO: Checking servicesextinfo...
Alignak: INFO: 	Checked 0 servicesextinfo
Alignak: INFO: Checking checkmodulations...
Alignak: INFO: 	Checked 0 checkmodulations
Alignak: INFO: Checking macromodulations...
Alignak: INFO: 	Checked 0 macromodulations
Alignak: INFO: Checking realms...
Alignak: INFO: 	Checked 1 realms
Alignak: INFO: Checking servicedependencies...
Alignak: INFO: 	Checked 0 servicedependencies
Alignak: INFO: Checking hostdependencies...
Alignak: INFO: 	Checked 0 hostdependencies
Alignak: INFO: Checking arbiters...
Alignak: INFO: 	Checked 1 arbiters
Alignak: INFO: Checking schedulers...
Alignak: INFO: 	Checked 1 schedulers
Alignak: INFO: Checking reactionners...
Alignak: INFO: 	Checked 1 reactionners
Alignak: INFO: Checking pollers...
Alignak: INFO: 	Checked 1 pollers
Alignak: INFO: Checking brokers...
Alignak: INFO: 	Checked 1 brokers
Alignak: INFO: Checking receivers...
Alignak: INFO: 	Checked 0 receivers
Alignak: INFO: Checking resultmodulations...
Alignak: INFO: 	Checked 0 resultmodulations
Alignak: INFO: Checking businessimpactmodulations...
Alignak: INFO: 	Checked 0 businessimpactmodulations
Alignak: INFO: Creating packs for realms
Alignak: INFO: Number of hosts in the realm Default: 2 (distributed in 1 linked packs)
Alignak: INFO: Number of Contacts : 1
Alignak: INFO: Number of Hosts : 2
Alignak: INFO: Number of Services : 1
Alignak: INFO: Number of Commands : 10
Alignak: INFO: Total number of hosts in all realms: 2
Alignak: INFO: [Arbiter] Serializing the configurations...
Alignak: INFO: Using the default serialization pass
Alignak: INFO: Modules directory: modules
Alignak: INFO: Modules directory: modules
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 1 test in 0.034s

FAILED (failures=1)
(alignak) ✘ ~/work/work/SFL/Supervision/alignak/test [Enh_C0103|…5⚑ 4]
gstarck@taf 10:02 $
```

@Seb-Solon  or @ddurieux  :  Can one of you (or both) check if you get the same error on your side for that particular test case ??

**Comment by gst** [comment]
Correction: the failure is also occuring in master & develop branch, so it's not related to this PR.
opened another one with this prob: https://github.com/Alignak-monitoring/alignak/issues/164

Reviewing: 5% done..

**Comment by Seb-Solon** [comment]
Related to #4, #87, #262 and naparuba/shinken#1393 .

**Pull request merged**
